import type { Breach, Severity } from "./types";

/**
 * services.ts — Catalogue des services connus → types de données
 * typiquement compromises + sévérité.
 *
 * XposedOrNot renvoie uniquement les NOMS des services. Ce catalogue
 * permet d'enrichir chaque fuite avec des types de données plausibles
 * (basés sur les fuites documentées publiquement) et une sévérité.
 * Les services inconnus reçoivent un profil générique prudent.
 */

interface ServiceProfile {
  severity: Severity;
  dataTypes: string[];
}

const CATALOG: Record<string, ServiceProfile> = {
  // ── Tech / social ─────────────────────────────────────────
  adobe: { severity: "critical", dataTypes: ["Email addresses", "Passwords (hashed)", "IP addresses", "Names"] },
  "adobe acrobat": { severity: "critical", dataTypes: ["Email addresses", "Passwords (hashed)", "IP addresses"] },
  facebook: { severity: "high", dataTypes: ["Email addresses", "Phone numbers", "Names", "Usernames"] },
  instagram: { severity: "high", dataTypes: ["Email addresses", "Phone numbers", "Names", "Usernames"] },
  twitter: { severity: "high", dataTypes: ["Email addresses", "Usernames", "Phone numbers"] },
  "x (twitter)": { severity: "high", dataTypes: ["Email addresses", "Usernames", "Phone numbers"] },
  linkedin: { severity: "high", dataTypes: ["Email addresses", "Names", "Job titles", "Company names"] },
  google: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  github: { severity: "high", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  amazon: { severity: "critical", dataTypes: ["Email addresses", "Names", "Physical addresses", "Payment data"] },
  apple: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  microsoft: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  outlook: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  hotmail: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  yahoo: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  aol: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  icloud: { severity: "critical", dataTypes: ["Email addresses", "Names", "Phone numbers", "Payment data"] },
  dropbox: { severity: "high", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  netflix: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  spotify: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  twitch: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  discord: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  reddit: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  quora: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  pinterest: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  snapchat: { severity: "medium", dataTypes: ["Email addresses", "Phone numbers", "Names"] },
  telegram: { severity: "medium", dataTypes: ["Phone numbers", "Names"] },
  whatsapp: { severity: "medium", dataTypes: ["Phone numbers", "Names"] },
  viber: { severity: "medium", dataTypes: ["Phone numbers", "Names"] },
  skype: { severity: "medium", dataTypes: ["Email addresses", "Phone numbers", "Names"] },
  signal: { severity: "medium", dataTypes: ["Phone numbers"] },
  tiktok: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Location data"] },
  youtube: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  wechat: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  weibo: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  line: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  kakao: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  zalo: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  qq: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  bilibili: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  zhihu: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  xiaohongshu: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  alipay: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  taobao: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  jd: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "jd.com": { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  meituan: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Payment data"] },
  netease: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  "qq mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "163 mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "126 mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "sina mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "tencent mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "proton mail": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  tutanota: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "mail.com": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  gmx: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "web.de": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "gmx.de": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "freenet.de": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "gmx.at": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "gmx.ch": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "bluewin.ch": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  swisscom: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  sunrise: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  upc: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  orange: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  sfr: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  free: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  bouygues: { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  "nrj mobile": { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  "red by sfr": { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  "la poste": { severity: "medium", dataTypes: ["Email addresses", "Names", "Phone numbers"] },
  "canal+": { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  arte: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france tv": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  tf1: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  m6: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  w9: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  c8: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  cstar: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "6play": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  d8: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  gulli: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "nrj 12": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  tmc: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  tfx: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  bfmtv: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  cnews: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  lci: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france 2": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france 3": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france 4": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france 5": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france info": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france inter": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france culture": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "france musique": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  rfi: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "le monde": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "le figaro": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "les echo": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  liberation: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "le point": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  marianne: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  mediapart: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "le canard enchaîne": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  "lecanard enchaine": { severity: "low", dataTypes: ["Email addresses", "Names"] },

  // ── E-commerce / paiement ─────────────────────────────────
  ebay: { severity: "high", dataTypes: ["Email addresses", "Names", "Physical addresses", "Payment data"] },
  paypal: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data", "IP addresses"] },
  venmo: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  coinbase: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  binance: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  uber: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Payment data"] },
  lyft: { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Payment data"] },
  airbnb: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "booking.com": { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  tripadvisor: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  shopify: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  stripe: { severity: "critical", dataTypes: ["Email addresses", "Payment data"] },
  square: { severity: "critical", dataTypes: ["Email addresses", "Payment data"] },
  intuit: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "turbo tax": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  chase: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "bank of america": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "capital one": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "wells fargo": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  citibank: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  hsbc: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  barclays: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  santander: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "bnp paribas": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "crédit agricole": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  sogebanque: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  boursorama: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  leboncoin: { severity: "high", dataTypes: ["Email addresses", "Phone numbers", "Names"] },
  vinted: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  zalando: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  decathlon: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  fnac: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  cdiscount: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  g2a: { severity: "high", dataTypes: ["Email addresses", "Payment data"] },
  kinguin: { severity: "high", dataTypes: ["Email addresses", "Payment data"] },
  gumroad: { severity: "medium", dataTypes: ["Email addresses", "Payment data"] },
  patreon: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  substack: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  ghost: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  blog: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  podcast: { severity: "low", dataTypes: ["Email addresses", "Names"] },
  newsletter: { severity: "low", dataTypes: ["Email addresses", "Names"] },

  // ── Gaming ────────────────────────────────────────────────
  gaming: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "Payment data"] },
  steam: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "Payment data"] },
  playstation: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  xbox: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  nintendo: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  roblox: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "Payment data"] },
  minecraft: { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  "epic games": { severity: "medium", dataTypes: ["Email addresses", "Usernames", "Payment data"] },
  "battle.net": { severity: "medium", dataTypes: ["Email addresses", "Usernames", "Payment data"] },

  // ── Dev / cloud ───────────────────────────────────────────
  gitlab: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  stackoverflow: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  wordpress: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  npm: { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  pypi: { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  rubygems: { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  "crates.io": { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  "docker hub": { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  heroku: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  netlify: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  vercel: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  cloudflare: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  digitalocean: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  aws: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  gcp: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  azure: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  atlassian: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  jira: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  bitbucket: { severity: "medium", dataTypes: ["Email addresses", "Usernames"] },
  slack: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  zoom: { severity: "medium", dataTypes: ["Email addresses", "Names", "IP addresses"] },
  webex: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  teams: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  meet: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  hangouts: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  trello: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  asana: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  "monday.com": { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  linear: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  confluence: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  notion: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  airtable: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  figma: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  canva: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  dribbble: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  behance: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  codepen: { severity: "low", dataTypes: ["Email addresses", "Usernames"] },
  vimeo: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  tumblr: { severity: "medium", dataTypes: ["Email addresses", "Usernames", "IP addresses"] },
  medium: { severity: "medium", dataTypes: ["Email addresses", "Names"] },

  // ── Santé / identité / finance ────────────────────────────
  doctissimo: { severity: "high", dataTypes: ["Email addresses", "Names", "Dates of birth"] },
  doctolib: { severity: "critical", dataTypes: ["Email addresses", "Names", "Medical data"] },
  hospital: { severity: "critical", dataTypes: ["Names", "Dates of birth", "Medical records", "Insurance data"] },
  clinic: { severity: "critical", dataTypes: ["Names", "Dates of birth", "Medical records"] },
  pharmacy: { severity: "critical", dataTypes: ["Names", "Prescriptions", "Insurance data"] },
  dental: { severity: "high", dataTypes: ["Names", "Dates of birth", "Insurance data"] },
  insurance: { severity: "critical", dataTypes: ["Names", "Dates of birth", "Insurance data", "Medical data"] },
  "insurance company": { severity: "critical", dataTypes: ["Names", "Dates of birth", "Insurance data"] },
  bank: { severity: "critical", dataTypes: ["Names", "Payment data", "Bank account numbers"] },
  "credit union": { severity: "critical", dataTypes: ["Names", "Payment data", "Bank account numbers"] },
  "credit bureau": { severity: "critical", dataTypes: ["Names", "Dates of birth", "Credit history", "Payment data"] },
  mortgage: { severity: "critical", dataTypes: ["Names", "Payment data", "Credit history"] },
  loan: { severity: "critical", dataTypes: ["Names", "Payment data", "Credit history"] },
  "student loan": { severity: "critical", dataTypes: ["Names", "Payment data", "Credit history"] },
  tax: { severity: "critical", dataTypes: ["Names", "Payment data", "Government ids"] },
  "tax office": { severity: "critical", dataTypes: ["Names", "Government ids", "Payment data"] },
  government: { severity: "critical", dataTypes: ["Names", "Government ids", "Dates of birth"] },
  "voter registry": { severity: "critical", dataTypes: ["Names", "Dates of birth", "Voting records"] },
  census: { severity: "high", dataTypes: ["Names", "Dates of birth", "Physical addresses"] },
  court: { severity: "critical", dataTypes: ["Names", "Court records", "Criminal records"] },
  police: { severity: "critical", dataTypes: ["Names", "Criminal records", "Warrants"] },
  prison: { severity: "critical", dataTypes: ["Names", "Criminal records"] },
  immigration: { severity: "critical", dataTypes: ["Names", "Passport numbers", "Government ids"] },
  embassy: { severity: "critical", dataTypes: ["Names", "Passport numbers"] },
  "passport office": { severity: "critical", dataTypes: ["Names", "Passport numbers"] },
  "driver license": { severity: "critical", dataTypes: ["Names", "Driver license numbers", "Dates of birth"] },
  dmv: { severity: "critical", dataTypes: ["Names", "Driver license numbers", "Dates of birth"] },
  "social security": { severity: "critical", dataTypes: ["Names", "SSNs", "Dates of birth"] },
  "national id": { severity: "critical", dataTypes: ["Names", "National ids", "Dates of birth"] },
  "vehicle registry": { severity: "high", dataTypes: ["Names", "License plates", "Vehicle data"] },
  "background check": { severity: "critical", dataTypes: ["Names", "Dates of birth", "Physical addresses", "Criminal records"] },
  "people search": { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Physical addresses"] },
  "data broker": { severity: "high", dataTypes: ["Email addresses", "Names", "Phone numbers", "Physical addresses", "Dates of birth"] },

  // ── Dating / adult ────────────────────────────────────────
  dating: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  tinder: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  bumble: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  hinge: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  match: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  okcupid: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  grindr: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Location data"] },
  scruff: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Location data"] },
  her: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  happn: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos", "Location data"] },
  "coffee meets bagel": { severity: "high", dataTypes: ["Email addresses", "Names", "Photos"] },
  badoo: { severity: "high", dataTypes: ["Email addresses", "Names", "Photos"] },
  "ashley madison": { severity: "critical", dataTypes: ["Email addresses", "Names", "Photos", "Dates of birth"] },
  adult: { severity: "critical", dataTypes: ["Email addresses", "Names", "Photos", "Payment data"] },
  porn: { severity: "critical", dataTypes: ["Email addresses", "Names", "Photos", "Payment data"] },
  onlyfans: { severity: "critical", dataTypes: ["Email addresses", "Names", "Photos", "Payment data"] },
  fanvue: { severity: "critical", dataTypes: ["Email addresses", "Names", "Photos", "Payment data"] },

  // ── Casino / betting ──────────────────────────────────────
  casino: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  betting: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  sportsbook: { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  lottery: { severity: "high", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "crypto exchange": { severity: "critical", dataTypes: ["Email addresses", "Names", "Payment data"] },
  wallet: { severity: "critical", dataTypes: ["Email addresses", "Payment data"] },
  exchange: { severity: "critical", dataTypes: ["Email addresses", "Payment data"] },
  stake: { severity: "critical", dataTypes: ["Email addresses", "Payment data"] },

  // ── Éducation / fitness ───────────────────────────────────
  university: { severity: "high", dataTypes: ["Email addresses", "Names", "Dates of birth"] },
  college: { severity: "high", dataTypes: ["Email addresses", "Names", "Dates of birth"] },
  school: { severity: "medium", dataTypes: ["Email addresses", "Names", "Dates of birth"] },
  udemy: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  coursera: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  edx: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  skillshare: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  codecademy: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  pluralsight: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  "khan academy": { severity: "low", dataTypes: ["Email addresses", "Names"] },
  duolingo: { severity: "medium", dataTypes: ["Email addresses", "Names"] },
  babbel: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  italki: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  preply: { severity: "medium", dataTypes: ["Email addresses", "Names", "Payment data"] },
  gym: { severity: "medium", dataTypes: ["Email addresses", "Names", "Fitness data"] },
  "fitness app": { severity: "medium", dataTypes: ["Email addresses", "Fitness data", "Location data"] },
  "sleep tracker": { severity: "medium", dataTypes: ["Email addresses", "Sleep data"] },
  smartwatch: { severity: "medium", dataTypes: ["Email addresses", "Fitness data", "Location data"] },
  "smart speaker": { severity: "medium", dataTypes: ["Email addresses", "Voice data"] },
  "smart home": { severity: "medium", dataTypes: ["Email addresses", "Device ids", "Location data"] },
};

/** Profil générique pour un service inconnu (prudent). */
const GENERIC: ServiceProfile = {
  severity: "medium",
  dataTypes: ["Email addresses", "IP addresses"],
};

const ORDER: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
  safe: 4,
};

/**
 * Enrichit une liste de noms de services (XposedOrNot) en Breach[].
 * Tri par sévérité décroissante, dédupliqué.
 */
export function enrichBreaches(serviceNames: string[]): Breach[] {
  const seen = new Set<string>();
  const breaches: Breach[] = [];

  for (const raw of serviceNames) {
    const name = raw.trim();
    if (!name) continue;
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);

    const profile = CATALOG[key] ?? GENERIC;
    breaches.push({
      service: name,
      severity: profile.severity,
      dataTypes: profile.dataTypes,
    });
  }

  breaches.sort((a, b) => ORDER[a.severity] - ORDER[b.severity]);
  return breaches;
}
